local ls = require("luasnip") -- Import LuaSnip
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("css", {
  s("cssboiler", {
    t({
      "/* || CSS RESET */",
      "* {",
      "    margin: 0;",
      "    padding: 0;",
      "    box-sizing: border-box;",
      "}",
      "",
      "/* || ROOT VARIABLES */",
      ":root {",
      "    --primary-color: ",
    }),
    i(1, "#3498db"),
    t({ ";", "    --secondary-color: " }),
    i(2, "#2ecc71"),
    t({ ";", "    --font-size: " }),
    i(3, "16px"),
    t({ ";", "    --font-family: " }),
    i(4, "'Poppins', sans-serif"),
    t({ ";", "    --container-width: " }),
    i(5, "1200px"),
    t({
      ";",
      "}",
      "",
      "/* || GLOBAL STYLES */",
      "body {",
      "    font-family: var(--font-family);",
      "    font-size: var(--font-size);",
      "    background-color: var(--primary-color);",
      "    color: white;",
      "    display: flex;",
      "    justify-content: center;",
      "    align-items: center;",
      "    min-height: 100vh;",
      "}",
      "",
      "/* || UTILITY CLASSES */",
      ".container {",
      "    max-width: var(--container-width);",
      "    margin: 0 auto;",
      "    padding: 20px;",
      "}",
      "",
      ".btn {",
      "    display: inline-block;",
      "    padding: 10px 20px;",
      "    border-radius: 5px;",
      "    text-align: center;",
      "    cursor: pointer;",
      "    background-color: var(--secondary-color);",
      "    color: white;",
      "    border: none;",
      "    transition: 0.3s;",
      "}",
      "",
      ".btn:hover {",
      "    background-color: var(--secondary-color);",
      "}",
    }),
  }),
})
